version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception-network
    restart: always

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-network    
    restart: always

volumes:
  db-data:
  wp-data:

networks:
  inception-network:
    driver: bridge
